#!/usr/bin/env bash

# ---------------------------------------------
# ---------- Configuration --------------------
# ---------------------------------------------

# Nothing to configure at this time.

# ---------------------------------------------
# ---------- Functions ------------------------
# ---------------------------------------------

. /bootstrap/assets/bash/funcs;

# ---------------------------------------------
# ---------- Check Setup State ----------------
# ---------------------------------------------

if [[ -f /etc/bootstrap/.wordpress-complete ]]; then
	exit 0; # Nothing more to do here.
fi; # End conditional check.

# ---------------------------------------------
# ---------- Run Setup Routines ---------------
# ---------------------------------------------

# Download and install the latest version of WordPress.

curl --location --output /tmp/wordpress-latest.zip http://wordpress.org/latest.zip;
unzip -qq -d /tmp/wordpress-latest /tmp/wordpress-latest.zip;

cp --force --recursive /tmp/wordpress-latest/wordpress/* /app/src;
cp --force /bootstrap/assets/wordpress/.wp-config.php /app/src/wp-config.php;

rm -r /tmp/wordpress-latest && rm /tmp/wordpress-latest.zip;

# Create theme/plugin symlinks if possible.

for wp_dir in  '/wordpress' \
					'/jaswsinc-wordpress' \
					'/websharks-wordpress' ; do

	# Create theme symlinks if possible.

	if [[ -d "$wp_dir"/themes ]]; then
		for dir in "$wp_dir"/themes/*; do
			rm --force /app/src/wp-content/themes/"$(basename "$dir")";

			if [[ -d "$dir"/"$(basename "$dir")" ]]; then
				ln --symbolic --no-target-directory "$dir"/"$(basename "$dir")" /app/src/wp-content/themes/"$(basename "$dir")";
			elif [[ -d "$dir" ]]; then # Not in a nested sub-directory; i.e., this is the theme directory?
				ln --symbolic --no-target-directory "$dir" /app/src/wp-content/themes/"$(basename "$dir")";
			fi;
		done;
	fi;
	# Create plugin symlinks if possible.

	if [[ -d "$wp_dir"/plugins ]]; then
		for dir in "$wp_dir"/plugins/*; do
			rm --force /app/src/wp-content/plugins/"$(basename "$dir")";

			if [[ -d "$dir"/"$(basename "$dir")" ]]; then
				ln --symbolic --no-target-directory "$dir"/"$(basename "$dir")" /app/src/wp-content/plugins/"$(basename "$dir")";
			elif [[ -d "$dir" ]]; then # Not in a nested sub-directory; i.e., this is the plugin directory?
				ln --symbolic --no-target-directory "$dir" /app/src/wp-content/plugins/"$(basename "$dir")";
			fi;
		done;
	fi;

done; # End WordPress symlinks.

# Mark setup as being complete.

touch /etc/bootstrap/.wordpress-complete;
