#!/usr/bin/env bash

# ---------------------------------------------
# ---------- Configuration --------------------
# ---------------------------------------------

DIRNAME="$(dirname "${BASH_SOURCE[0]}")";

# ---------------------------------------------
# ---------- Check Setup State ----------------
# ---------------------------------------------

if [[ -f "$DIRNAME"/.vagrant/.bootstrap-complete ]]; then

  if [[ "$OSTYPE" == 'darwin'* ]]; then
    echo 'Flushing DNS on Mac OS X; requires sudo...';
    sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder;
  fi;
  exit 0; # Nothing more.

fi; # End conditional check.

# ---------------------------------------------
# ---------- Run Setup Routines ---------------
# ---------------------------------------------

if [[ "$OSTYPE" == 'darwin'* ]]; then
  echo 'Flushing DNS on Mac OS X; requires sudo...';
  sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder;
fi;

# Mark setup as being complete.

touch "$DIRNAME"/.vagrant/.bootstrap-complete;
